# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=TheAnhDark@412
    ports:
      - '6603:3306'
    volumes:
      - E:\Dockers\Mysql\db:/var/lib/mysql
      - E:\Dockers\Mysql\cnf.d:/etc/my.cnf.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080